using Microsoft.VisualStudio.Shell;
using Microsoft.VisualStudio.Shell.Interop;
using SlnxMermaid.Core.Config;
using SlnxMermaid.Core.Extensions;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace SlnxMermaidVsix
{
    internal sealed class MermaidConfigBootstrapper
    {
        private readonly AsyncPackage package;
        private readonly MermaidOutputService outputService;

        public MermaidConfigBootstrapper(AsyncPackage package)
        {
            this.package = package ?? throw new ArgumentNullException(nameof(package));
            this.outputService = new MermaidOutputService(package);
        }

        public async Task EnsureConfigFileExistsAsync(
            string configPath,
            string solutionPath,
            IVsOutputWindowPane pane,
            CancellationToken cancellationToken)
        {
            if (File.Exists(configPath))
                return;

            var defaultConfig = this.CreateDefaultConfig(solutionPath);

            var yaml = new StringBuilder()
                .AppendLine("# Auto-generated by Slnx Mermaid Visual Studio extension")
                .AppendLine(defaultConfig.ToYaml())
                .ToString();

            cancellationToken.ThrowIfCancellationRequested();

            using (var stream = new FileStream(
                configPath,
                FileMode.Create,
                FileAccess.Write,
                FileShare.None,
                4096,
                useAsync: true))
            using (var writer = new StreamWriter(stream))
            {
                cancellationToken.ThrowIfCancellationRequested();
                await writer.WriteAsync(yaml);
            }

            await this.outputService.LogAsync(pane,
                $"Configuration file was missing and has been created: {configPath}");

            VsShellUtilities.OpenDocument(this.package, configPath);
        }

        private SlnxMermaidConfig CreateDefaultConfig(string solutionPath)
        {
            return new SlnxMermaidConfig
            {
                Solution = Path.GetFileName(solutionPath),
                Output = new OutputConfig
                {
                    File = "dependency-graph-mermaid.md"
                },
                Naming = new NamingConfig
                {
                    StripPrefix =
                        $"{Path.GetFileNameWithoutExtension(solutionPath)}_",
                    Aliases = new Dictionary<string, string>()
                },
                Filters = new FilterConfig
                {
                    Exclude = new string[]
                    {
                        "Test","Tests","Testing","Mock","Mocks",
                        "Stub","Stubs","Fake","Fakes","Enums",
                        "AppHost","WebHost","ServiceDefaults","Dto"
                    }.ToList()
                },
            };
        }

    }
}
