//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlnxMermaidVsix.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SlnxMermaidVsix.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Auto-generated by Slnx Mermaid Visual Studio extension.
        /// </summary>
        internal static string AutoGeneratedConfigComment {
            get {
                return ResourceManager.GetString("AutoGeneratedConfigComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram generation is already running. Wait for completion before starting again..
        /// </summary>
        internal static string CommandAlreadyRunningMessage {
            get {
                return ResourceManager.GetString("CommandAlreadyRunningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file was missing and has been created: {0}.
        /// </summary>
        internal static string ConfigCreatedMessageFormat {
            get {
                return ResourceManager.GetString("ConfigCreatedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dependency-graph-mermaid.md.
        /// </summary>
        internal static string DefaultOutputFile {
            get {
                return ResourceManager.GetString("DefaultOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to acquire DTE service..
        /// </summary>
        internal static string ErrorAcquireDteService {
            get {
                return ResourceManager.GetString("ErrorAcquireDteService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to acquire OleMenuCommandService..
        /// </summary>
        internal static string ErrorAcquireMenuCommandService {
            get {
                return ResourceManager.GetString("ErrorAcquireMenuCommandService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to acquire the output pane..
        /// </summary>
        internal static string ErrorAcquireOutputPane {
            get {
                return ResourceManager.GetString("ErrorAcquireOutputPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to acquire SVsOutputWindow service..
        /// </summary>
        internal static string ErrorAcquireOutputWindowService {
            get {
                return ResourceManager.GetString("ErrorAcquireOutputWindowService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the solution directory..
        /// </summary>
        internal static string ErrorDetermineSolutionDirectory {
            get {
                return ResourceManager.GetString("ErrorDetermineSolutionDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mermaid diagram generation failed. See &apos;{0}&apos; in the Output window for details.
        ///
        ///{1}.
        /// </summary>
        internal static string ErrorGenerationFailedDialogFormat {
            get {
                return ResourceManager.GetString("ErrorGenerationFailedDialogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppHost.
        /// </summary>
        internal static string ExcludeAppHost {
            get {
                return ResourceManager.GetString("ExcludeAppHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dto.
        /// </summary>
        internal static string ExcludeDto {
            get {
                return ResourceManager.GetString("ExcludeDto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enums.
        /// </summary>
        internal static string ExcludeEnums {
            get {
                return ResourceManager.GetString("ExcludeEnums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fake.
        /// </summary>
        internal static string ExcludeFake {
            get {
                return ResourceManager.GetString("ExcludeFake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fakes.
        /// </summary>
        internal static string ExcludeFakes {
            get {
                return ResourceManager.GetString("ExcludeFakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mock.
        /// </summary>
        internal static string ExcludeMock {
            get {
                return ResourceManager.GetString("ExcludeMock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mocks.
        /// </summary>
        internal static string ExcludeMocks {
            get {
                return ResourceManager.GetString("ExcludeMocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceDefaults.
        /// </summary>
        internal static string ExcludeServiceDefaults {
            get {
                return ResourceManager.GetString("ExcludeServiceDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stub.
        /// </summary>
        internal static string ExcludeStub {
            get {
                return ResourceManager.GetString("ExcludeStub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stubs.
        /// </summary>
        internal static string ExcludeStubs {
            get {
                return ResourceManager.GetString("ExcludeStubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string ExcludeTest {
            get {
                return ResourceManager.GetString("ExcludeTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing.
        /// </summary>
        internal static string ExcludeTesting {
            get {
                return ResourceManager.GetString("ExcludeTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests.
        /// </summary>
        internal static string ExcludeTests {
            get {
                return ResourceManager.GetString("ExcludeTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebHost.
        /// </summary>
        internal static string ExcludeWebHost {
            get {
                return ResourceManager.GetString("ExcludeWebHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a solution file first, then run &apos;Generate Mermaid Diagram&apos;..
        /// </summary>
        internal static string InfoOpenSolutionFirst {
            get {
                return ResourceManager.GetString("InfoOpenSolutionFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing solution graph: {0}.
        /// </summary>
        internal static string LogAnalyzingSolutionFormat {
            get {
                return ResourceManager.GetString("LogAnalyzingSolutionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Mermaid Diagram command invoked..
        /// </summary>
        internal static string LogCommandInvoked {
            get {
                return ResourceManager.GetString("LogCommandInvoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram written to: {0}.
        /// </summary>
        internal static string LogDiagramWrittenFormat {
            get {
                return ResourceManager.GetString("LogDiagramWrittenFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovered {0} projects..
        /// </summary>
        internal static string LogDiscoveredProjectsFormat {
            get {
                return ResourceManager.GetString("LogDiscoveredProjectsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emitting Mermaid diagram....
        /// </summary>
        internal static string LogEmittingMermaid {
            get {
                return ResourceManager.GetString("LogEmittingMermaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation failed: {0}.
        /// </summary>
        internal static string LogGenerationFailedFormat {
            get {
                return ResourceManager.GetString("LogGenerationFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation skipped because no solution is currently loaded..
        /// </summary>
        internal static string LogGenerationSkippedNoSolution {
            get {
                return ResourceManager.GetString("LogGenerationSkippedNoSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading config: {0}.
        /// </summary>
        internal static string LogLoadingConfigFormat {
            get {
                return ResourceManager.GetString("LogLoadingConfigFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected solution: {0} {1} Invoking SlnxMermaid.Core with argument: --config &quot;{2}&quot;.
        /// </summary>
        internal static string LogSelectedSolutionAndConfigFormat {
            get {
                return ResourceManager.GetString("LogSelectedSolutionAndConfigFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0:HH:mm:ss}] {1}{2}.
        /// </summary>
        internal static string OutputLogFormat {
            get {
                return ResourceManager.GetString("OutputLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slnx Mermaid.
        /// </summary>
        internal static string OutputPaneTitle {
            get {
                return ResourceManager.GetString("OutputPaneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mermaid diagram generation failed..
        /// </summary>
        internal static string StatusGenerationFailed {
            get {
                return ResourceManager.GetString("StatusGenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating Mermaid diagram....
        /// </summary>
        internal static string StatusGenerationInProgress {
            get {
                return ResourceManager.GetString("StatusGenerationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No solution loaded. Generation skipped..
        /// </summary>
        internal static string StatusGenerationSkippedNoSolution {
            get {
                return ResourceManager.GetString("StatusGenerationSkippedNoSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Mermaid diagram generation....
        /// </summary>
        internal static string StatusGenerationStarting {
            get {
                return ResourceManager.GetString("StatusGenerationStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the configuration file was denied. Check file permissions and try again..
        /// </summary>
        internal static string DialogConfigAccessDenied {
            get {
                return ResourceManager.GetString("DialogConfigAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Please verify the file path and try again..
        /// </summary>
        internal static string DialogConfigReadFailedFormat {
            get {
                return ResourceManager.GetString("DialogConfigReadFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while generating the diagram. See the Output window for details..
        /// </summary>
        internal static string DialogUnexpectedGenerationError {
            get {
                return ResourceManager.GetString("DialogUnexpectedGenerationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file contains invalid YAML. Please fix it and try again..
        /// </summary>
        internal static string DialogYamlInvalid {
            get {
                return ResourceManager.GetString("DialogYamlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file contains invalid YAML at {0}. Please fix it and try again..
        /// </summary>
        internal static string DialogYamlInvalidWithLocationFormat {
            get {
                return ResourceManager.GetString("DialogYamlInvalidWithLocationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to column {0}.
        /// </summary>
        internal static string LocationColumnFormat {
            get {
                return ResourceManager.GetString("LocationColumnFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to line {0}, column {1}.
        /// </summary>
        internal static string LocationLineColumnFormat {
            get {
                return ResourceManager.GetString("LocationLineColumnFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to line {0}.
        /// </summary>
        internal static string LocationLineFormat {
            get {
                return ResourceManager.GetString("LocationLineFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the configuration file was denied..
        /// </summary>
        internal static string StatusConfigAccessDenied {
            get {
                return ResourceManager.GetString("StatusConfigAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file was not found..
        /// </summary>
        internal static string StatusConfigFileNotFound {
            get {
                return ResourceManager.GetString("StatusConfigFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read the configuration file..
        /// </summary>
        internal static string StatusConfigReadFailed {
            get {
                return ResourceManager.GetString("StatusConfigReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file has invalid YAML..
        /// </summary>
        internal static string StatusYamlInvalid {
            get {
                return ResourceManager.GetString("StatusYamlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file has invalid YAML at {0}..
        /// </summary>
        internal static string StatusYamlInvalidWithLocationFormat {
            get {
                return ResourceManager.GetString("StatusYamlInvalidWithLocationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_.
        /// </summary>
        internal static string StripPrefixFormat {
            get {
                return ResourceManager.GetString("StripPrefixFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mermaid diagram generation completed successfully..
        /// </summary>
        internal static string SuccessGenerationCompleted {
            get {
                return ResourceManager.GetString("SuccessGenerationCompleted", resourceCulture);
            }
        }
    }
}
