// <auto-generated />
namespace SlnxMermaidVsix.Resources
{
    using System;
    using System.Globalization;
    using System.Resources;

    internal static class Strings
    {
        private static ResourceManager resourceManager;
        private static CultureInfo resourceCulture;

        private static ResourceManager ResourceManager =>
            resourceManager ?? (resourceManager = new ResourceManager("SlnxMermaidVsix.Resources.Strings", typeof(Strings).Assembly));

        internal static CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        internal static string OutputPaneTitle => ResourceManager.GetString(nameof(OutputPaneTitle), resourceCulture);
        internal static string ErrorAcquireMenuCommandService => ResourceManager.GetString(nameof(ErrorAcquireMenuCommandService), resourceCulture);
        internal static string ErrorAcquireDteService => ResourceManager.GetString(nameof(ErrorAcquireDteService), resourceCulture);
        internal static string ErrorAcquireOutputWindowService => ResourceManager.GetString(nameof(ErrorAcquireOutputWindowService), resourceCulture);
        internal static string ErrorAcquireOutputPane => ResourceManager.GetString(nameof(ErrorAcquireOutputPane), resourceCulture);
        internal static string OutputLogFormat => ResourceManager.GetString(nameof(OutputLogFormat), resourceCulture);
        internal static string AutoGeneratedConfigComment => ResourceManager.GetString(nameof(AutoGeneratedConfigComment), resourceCulture);
        internal static string ConfigCreatedMessageFormat => ResourceManager.GetString(nameof(ConfigCreatedMessageFormat), resourceCulture);
        internal static string DefaultOutputFile => ResourceManager.GetString(nameof(DefaultOutputFile), resourceCulture);
        internal static string StripPrefixFormat => ResourceManager.GetString(nameof(StripPrefixFormat), resourceCulture);
        internal static string ExcludeTest => ResourceManager.GetString(nameof(ExcludeTest), resourceCulture);
        internal static string ExcludeTests => ResourceManager.GetString(nameof(ExcludeTests), resourceCulture);
        internal static string ExcludeTesting => ResourceManager.GetString(nameof(ExcludeTesting), resourceCulture);
        internal static string ExcludeMock => ResourceManager.GetString(nameof(ExcludeMock), resourceCulture);
        internal static string ExcludeMocks => ResourceManager.GetString(nameof(ExcludeMocks), resourceCulture);
        internal static string ExcludeStub => ResourceManager.GetString(nameof(ExcludeStub), resourceCulture);
        internal static string ExcludeStubs => ResourceManager.GetString(nameof(ExcludeStubs), resourceCulture);
        internal static string ExcludeFake => ResourceManager.GetString(nameof(ExcludeFake), resourceCulture);
        internal static string ExcludeFakes => ResourceManager.GetString(nameof(ExcludeFakes), resourceCulture);
        internal static string ExcludeEnums => ResourceManager.GetString(nameof(ExcludeEnums), resourceCulture);
        internal static string ExcludeAppHost => ResourceManager.GetString(nameof(ExcludeAppHost), resourceCulture);
        internal static string ExcludeWebHost => ResourceManager.GetString(nameof(ExcludeWebHost), resourceCulture);
        internal static string ExcludeServiceDefaults => ResourceManager.GetString(nameof(ExcludeServiceDefaults), resourceCulture);
        internal static string ExcludeDto => ResourceManager.GetString(nameof(ExcludeDto), resourceCulture);
        internal static string LogLoadingConfigFormat => ResourceManager.GetString(nameof(LogLoadingConfigFormat), resourceCulture);
        internal static string LogAnalyzingSolutionFormat => ResourceManager.GetString(nameof(LogAnalyzingSolutionFormat), resourceCulture);
        internal static string LogDiscoveredProjectsFormat => ResourceManager.GetString(nameof(LogDiscoveredProjectsFormat), resourceCulture);
        internal static string LogEmittingMermaid => ResourceManager.GetString(nameof(LogEmittingMermaid), resourceCulture);
        internal static string LogDiagramWrittenFormat => ResourceManager.GetString(nameof(LogDiagramWrittenFormat), resourceCulture);
        internal static string LogCommandInvoked => ResourceManager.GetString(nameof(LogCommandInvoked), resourceCulture);
        internal static string ErrorDetermineSolutionDirectory => ResourceManager.GetString(nameof(ErrorDetermineSolutionDirectory), resourceCulture);
        internal static string LogSelectedSolutionAndConfigFormat => ResourceManager.GetString(nameof(LogSelectedSolutionAndConfigFormat), resourceCulture);
        internal static string SuccessGenerationCompleted => ResourceManager.GetString(nameof(SuccessGenerationCompleted), resourceCulture);
        internal static string LogGenerationFailedFormat => ResourceManager.GetString(nameof(LogGenerationFailedFormat), resourceCulture);
        internal static string ErrorGenerationFailedDialogFormat => ResourceManager.GetString(nameof(ErrorGenerationFailedDialogFormat), resourceCulture);
        internal static string LogGenerationSkippedNoSolution => ResourceManager.GetString(nameof(LogGenerationSkippedNoSolution), resourceCulture);
        internal static string InfoOpenSolutionFirst => ResourceManager.GetString(nameof(InfoOpenSolutionFirst), resourceCulture);
    }
}
