using Microsoft.VisualStudio.Shell;
using Microsoft.VisualStudio.Shell.Interop;
using SlnxMermaid.Core.Config;
using SlnxMermaid.Core.Extensions;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace SlnxMermaidVsix
{
    /// <summary>
    /// Odpowiada za przygotowanie domyślnej konfiguracji `slnx-mermaid.yml`
    /// w przypadku jej braku w katalogu rozwiązania.
    /// </summary>
    internal sealed class MermaidConfigBootstrapper
    {
        private readonly AsyncPackage package;
        private readonly MermaidOutputService outputService;

        /// <summary>
        /// Tworzy serwis bootstrapujący konfigurację.
        /// </summary>
        public MermaidConfigBootstrapper(AsyncPackage package)
        {
            this.package = package ?? throw new ArgumentNullException(nameof(package));
            outputService = new MermaidOutputService(package);
        }

        /// <summary>
        /// Zapewnia istnienie pliku konfiguracyjnego; gdy go brakuje, tworzy plik z domyślną treścią.
        /// </summary>
        public async Task EnsureConfigFileExistsAsync(
            string configPath,
            string solutionPath,
            IVsOutputWindowPane pane,
            CancellationToken cancellationToken)
        {
            if (File.Exists(configPath))
                return;

            var defaultConfig = CreateDefaultConfig(solutionPath);

            var yaml = new StringBuilder()
                .AppendLine("# Auto-generated by Slnx Mermaid Visual Studio extension")
                .AppendLine(defaultConfig.ToYaml())
                .ToString();

            cancellationToken.ThrowIfCancellationRequested();

            using (var stream = new FileStream(
                configPath,
                FileMode.Create,
                FileAccess.Write,
                FileShare.None,
                4096,
                useAsync: true))
            using (var writer = new StreamWriter(stream))
            {
                cancellationToken.ThrowIfCancellationRequested();
                await writer.WriteAsync(yaml);
            }

            await outputService.LogAsync(pane,
                $"Configuration file was missing and has been created: {configPath}");

            VsShellUtilities.OpenDocument(package, configPath);
        }

        /// <summary>
        /// Buduje domyślny obiekt konfiguracji na podstawie nazwy bieżącego rozwiązania.
        /// </summary>
        private SlnxMermaidConfig CreateDefaultConfig(string solutionPath)
        {
            return new SlnxMermaidConfig
            {
                Solution = Path.GetFileName(solutionPath),
                Output = new OutputConfig
                {
                    File = "dependency-graph-mermaid.md"
                },
                Naming = new NamingConfig
                {
                    StripPrefix =
                        $"{Path.GetFileNameWithoutExtension(solutionPath)}_",
                    Aliases = new Dictionary<string, string>()
                },
                Filters = new FilterConfig
                {
                    Exclude = new[]
                    {
                        "Test", "Tests", "Testing", "Mock", "Mocks",
                        "Stub", "Stubs", "Fake", "Fakes", "Enums",
                        "AppHost", "WebHost", "ServiceDefaults", "Dto"
                    }.ToList()
                },
            };
        }
    }
}
