name: CD-common-github-release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      prerelease:
        required: false
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ inputs.version }}
          name: v${{ inputs.version }}
          generate_release_notes: true
          prerelease: ${{ inputs.prerelease }}
