name: CI-vsix-build

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore
        run: msbuild SlnxMermaidVisualStudio.slnx /t:Restore

      - name: CI-vsix-build
        run: msbuild SlnxMermaidVisualStudio.slnx /p:Configuration=Release
