name: Release RC

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency:
  group: release-rc
  cancel-in-progress: false

jobs:
  nuget-rc:
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/reusable-release-nuget.yml
    with:
      channel: rc
    secrets: inherit

  vsix-rc:
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/reusable-release-vsix.yml
    with:
      channel: rc
    secrets: inherit
