name: Release

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

concurrency:
  group: release-prod
  cancel-in-progress: false

jobs:
  nuget-prod:
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/reusable-release-nuget.yml
    with:
      channel: prod
    secrets: inherit

  vsix-prod:
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/reusable-release-vsix.yml
    with:
      channel: prod
    secrets: inherit
